server:
  port: 5432
spring:
  datasource:
    url: jdbc:postgresql://ec2-54-80-122-11.compute-1.amazonaws.com:5432/d6cdukdobimrfq
    username: iwlaencwieivpk
    password:  22f96f99e63c713364b623b61497cd33bae30529a0d961242db87dfa05988faa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mareewsaja@gmail.com
    password: qybgwegehkeppick
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
